language: java

env:
  global:
    -secure: U7F8F5SZev/OD1CE5v5UzRkmU7v3qyqj1W2YFh64x3hMu8g4z6UiknT3cNXh/HyVU+Xb6Rdzmwrjne7LWemoYe0pZCCn/XpIvWhRmBGNBNHJ7BBu6ncNDuCcLfKkf8QdY/KptJNzQVYheFnHefzISbAy8ecrfRIsw7aEAI9Foh8=

after_success:
  - .travis/publish-packages.sh
