language: java

env:
  global:
  - secure: "kK5Oh473LtY4QSsnNqyH+nwkAplEVUrU+TBwmIgHlURPbzvllC0V8/f10mILNlZvGzWCXN0N4YlnLs7qNDbcyup8MKdGMX6d8ioGDHjO0/3d9cuuCOoD2v1WWO/Vcbn4JML82DHJgYnh71qVbSHNPM3Oj360tVe529uTluawmPY="
  
after_success:
- .travis/publish-packages.sh
