language: java

env:
  global:
    -secure: NWlduWdSL7oOIsRFJMDvfdbO5u11d9nZwE+9VI30bZZTyp/zJxePokzAE7z41OY0q2nt+gjq4D1sq02JHIAPOu7GXhD3EnaF1kmFIeDI62Bvw/Bc6KnREPZ+rbPB/IBCNHUcoDK3O5nd2L2/LI7+qe6thl7LBXsVWQ0BoXEP2UY=

after_success:
  - .travis/publish-packages.sh
